"""
One-time script: uploads all DSA lesson data from roadmap.js to DynamoDB (aquire-lessons table).
Run: python upload_lessons.py
"""
import os
import boto3
from dotenv import load_dotenv
from decimal import Decimal

load_dotenv()

# ── All lessons extracted from frontend/src/data/roadmap.js ──────────────────
LESSONS = [
    # Step 1
    {"title": "Things to Know in C++/Java/Python", "difficulty": "Easy", "step": "Step 1: Learn the Basics", "description": "Get familiar with the fundamental syntax and programming constructs of your chosen language (C++, Java, or Python). This includes data types, control flow (if/else, loops), functions, arrays, and basic I/O.\n\nTopics:\n• Variables, data types, type casting\n• Loops: for, while, do-while\n• Functions and recursion basics\n• Arrays and strings\n• Basic I/O", "key_concepts": ["variables", "loops", "functions", "arrays", "I/O"]},
    {"title": "Build-up Logical Thinking", "difficulty": "Easy", "step": "Step 1: Learn the Basics", "description": "Develop problem-solving intuition by practising pattern-based thinking. Break down problems into smaller sub-problems.\n\nTopics:\n• Pattern printing (stars, numbers, alphabets)\n• Recognising problem structure\n• Translating problem statement to code\n• Dry-running code mentally", "key_concepts": ["patterns", "problem-solving", "dry-run"]},
    {"title": "Learn STL / Java Collections", "difficulty": "Medium", "step": "Step 1: Learn the Basics", "description": "Master the Standard Template Library (C++) or Java Collections — pre-built optimised data structures used constantly in interviews.\n\nKey containers:\n• vector/ArrayList — dynamic arrays\n• map/HashMap — key-value pairs\n• set/HashSet — unique elements\n• stack, queue, priority_queue\n• pair / utility classes\n\nAlso: sorting, searching, built-in algorithms.", "key_concepts": ["vector", "map", "set", "stack", "queue", "priority_queue"]},
    {"title": "Know Basic Math Concepts", "difficulty": "Easy", "step": "Step 1: Learn the Basics", "description": "Strong mathematical foundation helps derive efficient solutions.\n\nTopics:\n• Count digits in a number\n• Reverse a number\n• Check palindrome number\n• GCD and LCM (Euclidean algorithm)\n• Check prime numbers\n• Sieve of Eratosthenes\n• Fast exponentiation", "key_concepts": ["GCD", "LCM", "prime", "sieve", "exponentiation"]},
    {"title": "Understand Basic Recursion", "difficulty": "Easy", "step": "Step 1: Learn the Basics", "description": "Recursion is a technique where a function calls itself to solve a smaller version of the same problem. It's the backbone of tree traversals, divide & conquer, and backtracking.\n\nTopics:\n• Understanding the call stack\n• Base case and recursive case\n• Factorial, Fibonacci\n• Print 1 to N and N to 1\n• Sum of first N numbers\n• Reverse array using recursion\n• Palindrome check via recursion", "key_concepts": ["call stack", "base case", "recursive case", "factorial", "fibonacci"]},
    {"title": "Learn Basic Hashing", "difficulty": "Easy", "step": "Step 1: Learn the Basics", "description": "Hashing allows O(1) average time store/retrieve. Powerful for optimising brute-force solutions.\n\nTopics:\n• Hash functions\n• Collision handling: chaining vs open addressing\n• Using maps and sets\n• Count frequency of elements\n• Two Sum using hashing\n• Find duplicates\n• Longest consecutive sequence", "key_concepts": ["hash function", "collision", "frequency count", "two sum"]},

    # Step 2
    {"title": "Selection Sort", "difficulty": "Easy", "step": "Step 2: Learn Important Sorting Techniques", "description": "Repeatedly find the minimum from unsorted portion and place at beginning.\n\nAlgorithm:\n1. Find minimum in unsorted subarray\n2. Swap with first element of unsorted portion\n3. Move boundary right\n\nTime: O(n²) all cases | Space: O(1)\nMakes at most n-1 swaps — useful when writes are costly.", "key_concepts": ["minimum selection", "in-place", "O(n²)"]},
    {"title": "Bubble Sort", "difficulty": "Easy", "step": "Step 2: Learn Important Sorting Techniques", "description": "Repeatedly compare adjacent elements and swap if wrong order. Larger elements bubble up.\n\nAlgorithm:\n1. Compare arr[j] and arr[j+1]\n2. Swap if arr[j] > arr[j+1]\n3. After each pass, largest element is in correct position\n\nTime: O(n²) worst/average, O(n) best (with optimization) | Space: O(1)", "key_concepts": ["adjacent swap", "bubble up", "O(n²)"]},
    {"title": "Insertion Sort", "difficulty": "Easy", "step": "Step 2: Learn Important Sorting Techniques", "description": "Build sorted array one element at a time by inserting each into its correct position.\n\nAlgorithm:\n1. Start from index 1\n2. Pick current element as 'key'\n3. Shift elements greater than key one position ahead\n4. Place key at correct position\n\nTime: O(n²) worst, O(n) best | Space: O(1)\nGreat for nearly-sorted arrays.", "key_concepts": ["key insertion", "shifting", "nearly-sorted"]},
    {"title": "Merge Sort", "difficulty": "Medium", "step": "Step 2: Learn Important Sorting Techniques", "description": "Divide and conquer: split in half, recursively sort each half, merge.\n\nAlgorithm:\n1. If ≤1 element, return\n2. Split into two halves\n3. Recursively sort each\n4. Merge sorted halves\n\nTime: O(n log n) all cases | Space: O(n)\nStable sort — preserves relative order of equal elements.", "key_concepts": ["divide and conquer", "merge", "stable sort", "O(n log n)"]},
    {"title": "Quick Sort", "difficulty": "Medium", "step": "Step 2: Learn Important Sorting Techniques", "description": "Pick pivot, partition into elements smaller/larger, recursively sort each part.\n\nAlgorithm:\n1. Choose pivot\n2. Partition around pivot\n3. Recursively sort subarrays\n\nTime: O(n log n) average, O(n²) worst | Space: O(log n)\nFastest in practice due to cache efficiency.", "key_concepts": ["pivot", "partition", "in-place", "cache efficiency"]},
    {"title": "Recursive Bubble Sort", "difficulty": "Medium", "step": "Step 2: Learn Important Sorting Techniques", "description": "Implement Bubble Sort using recursion.\n\nApproach:\n1. Base case: if n==1, return\n2. Do one pass for first n-1 elements\n3. Recursively call for n-1 elements\n\nTime: O(n²) | Space: O(n) due to recursion stack", "key_concepts": ["recursion", "bubble sort", "call stack"]},
    {"title": "Recursive Insertion Sort", "difficulty": "Medium", "step": "Step 2: Learn Important Sorting Techniques", "description": "Implement Insertion Sort using recursion.\n\nApproach:\n1. Base case: if n<=1, return\n2. Recursively sort first n-1 elements\n3. Insert last element (arr[n-1]) into correct position\n\nTime: O(n²) | Space: O(n) due to recursion stack", "key_concepts": ["recursion", "insertion sort", "call stack"]},

    # Step 3
    {"title": "Largest Element in an Array", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Find the largest element in an array of N integers.\n\nApproach:\n• Initialise max = arr[0]\n• Iterate: if arr[i] > max, update max\n• Return max\n\nTime: O(n) | Space: O(1)", "examples": [{"input": "arr = [3, 1, 4, 1, 5, 9, 2]", "output": "9"}, {"input": "arr = [10, 4, 3, 50, 23]", "output": "50"}], "key_concepts": ["linear scan", "max tracking"]},
    {"title": "Second Largest Element", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Find the second largest distinct element in one pass.\n\nApproach:\n• Track both largest and second largest\n• If arr[i] > largest: secondLargest=largest, largest=arr[i]\n• Else if arr[i] > secondLargest && arr[i] != largest: secondLargest=arr[i]\n\nTime: O(n) | Space: O(1)", "key_concepts": ["two variables", "distinct elements", "single pass"]},
    {"title": "Check if the array is sorted", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Check if array is sorted in non-decreasing order.\n\nApproach:\n• Iterate from index 1\n• If arr[i] < arr[i-1], return false\n• Return true\n\nTime: O(n) | Space: O(1)", "key_concepts": ["adjacent comparison", "non-decreasing"]},
    {"title": "Remove duplicates from Sorted array", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Remove duplicates in-place from sorted array, return count of unique elements.\n\nTwo Pointer approach:\n• i=0 tracks unique elements\n• j iterates from 1\n• If arr[j] != arr[i]: i++, arr[i]=arr[j]\n• Return i+1\n\nTime: O(n) | Space: O(1)", "key_concepts": ["two pointers", "in-place", "sorted array"]},
    {"title": "Left Rotate an array by one place", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Rotate array left by one position. First element goes to end.\n\nApproach:\n• Store arr[0] in temp\n• Shift all elements one position left\n• Place temp at last position\n\nTime: O(n) | Space: O(1)", "key_concepts": ["rotation", "shifting", "temp variable"]},
    {"title": "Left rotate an array by D places", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Rotate array left by D positions.\n\nOptimal (Reversal Algorithm):\n1. Reverse first D elements\n2. Reverse remaining n-D elements\n3. Reverse entire array\n\nTime: O(n) | Space: O(1)\nHandle D > n: use D = D % n", "key_concepts": ["reversal algorithm", "modulo", "in-place rotation"]},
    {"title": "Move Zeros to end", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Move all zeroes to end while maintaining relative order of non-zero elements.\n\nTwo Pointer:\n• j tracks next non-zero position\n• For each non-zero element, place at j, increment j\n• Fill remaining with 0\n\nTime: O(n) | Space: O(1)", "key_concepts": ["two pointers", "relative order", "in-place"]},
    {"title": "Linear Search", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Search for target in array, return its index or -1.\n\nApproach:\n• Iterate through array\n• If arr[i] == target, return i\n• Return -1 if not found\n\nTime: O(n) | Space: O(1)", "key_concepts": ["linear scan", "index return"]},
    {"title": "Find the missing number", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Given array of n-1 integers from 1 to n, find the missing number.\n\nApproach 1 (Sum Formula): Expected = n*(n+1)/2. Missing = expected - actual sum.\nApproach 2 (XOR): XOR all 1..n with all array elements.\n\nTime: O(n) | Space: O(1)", "examples": [{"input": "arr=[1,2,4,5], n=5", "output": "3"}, {"input": "arr=[2,3,4,5], n=5", "output": "1"}], "key_concepts": ["sum formula", "XOR trick", "1 to n"]},
    {"title": "Two Sum", "difficulty": "Easy", "step": "Step 3: Solve Problems on Arrays", "description": "Find indices of two numbers that add up to target.\n\nHashMap approach:\n• For each element, check if (target - arr[i]) exists in map\n• If yes, return [map[target-arr[i]], i]\n• Else store arr[i]->i in map\n\nTime: O(n) | Space: O(n)", "examples": [{"input": "arr=[2,7,11,15], target=9", "output": "[0,1]"}, {"input": "arr=[3,2,4], target=6", "output": "[1,2]"}], "key_concepts": ["hashmap", "complement", "O(1) lookup"]},
    {"title": "Sort an array of 0's 1's and 2's", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Sort array of 0s, 1s, 2s in O(n) without sorting algorithm.\n\nDutch National Flag (3 Pointers):\n• low=0, mid=0, high=n-1\n• arr[mid]==0: swap(arr[low],arr[mid]); low++; mid++\n• arr[mid]==1: mid++\n• arr[mid]==2: swap(arr[mid],arr[high]); high--\n\nTime: O(n) | Space: O(1)", "examples": [{"input": "arr=[0,2,1,2,0,1]", "output": "[0,0,1,1,2,2]"}], "key_concepts": ["Dutch National Flag", "three pointers", "in-place"]},
    {"title": "Majority Element (>n/2 times)", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Find element appearing more than n/2 times.\n\nBoyer-Moore Voting:\n• Track candidate and count\n• If count==0: candidate=arr[i]\n• If arr[i]==candidate: count++; else count--\n• Candidate is majority element\n\nTime: O(n) | Space: O(1)", "key_concepts": ["Boyer-Moore Voting", "candidate", "majority"]},
    {"title": "Kadane's Algorithm, maximum subarray sum", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Find contiguous subarray with largest sum.\n\nKadane's:\n• Maintain currentSum and maxSum\n• currentSum = max(arr[i], currentSum + arr[i])\n• maxSum = max(maxSum, currentSum)\n\nTime: O(n) | Space: O(1)\nEdge case: all negative → return maximum element.", "examples": [{"input": "arr=[-2,1,-3,4,-1,2,1,-5,4]", "output": "6 (subarray [4,-1,2,1])"}], "key_concepts": ["Kadane's algorithm", "currentSum", "maxSum"]},
    {"title": "Best time to buy and sell stock", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Find maximum profit from one buy and one sell.\n\nApproach:\n• Track minimum price seen so far\n• For each price: profit = price - minPrice; update maxProfit\n• Return maxProfit (0 if no profit)\n\nTime: O(n) | Space: O(1)", "examples": [{"input": "prices=[7,1,5,3,6,4]", "output": "5 (buy at 1, sell at 6)"}], "key_concepts": ["min tracking", "profit maximisation"]},
    {"title": "Rearrange array elements by sign", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Alternate positives and negatives starting with positive (equal counts assumed).\n\nApproach:\n• posIdx=0, negIdx=1\n• Place positives at even indices, negatives at odd indices\n\nTime: O(n) | Space: O(n)", "key_concepts": ["even/odd indices", "sign separation"]},
    {"title": "Next Permutation", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Find next lexicographically greater permutation in-place.\n\nAlgorithm:\n1. Find largest i where arr[i] < arr[i+1] from right\n2. Find largest j > i where arr[j] > arr[i]\n3. Swap arr[i] and arr[j]\n4. Reverse suffix from arr[i+1]\n\nIf no such i: reverse entire array.", "examples": [{"input": "arr=[1,2,3]", "output": "[1,3,2]"}, {"input": "arr=[3,2,1]", "output": "[1,2,3]"}], "key_concepts": ["lexicographic order", "suffix reverse", "two-pointer swap"]},
    {"title": "Leaders in an Array", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "A leader is greater than all elements to its right. Rightmost is always a leader.\n\nApproach:\n• Traverse right to left\n• Track running max from right\n• If arr[i] >= max: it's a leader, update max\n\nTime: O(n) | Space: O(1) extra", "key_concepts": ["right-to-left scan", "running maximum"]},
    {"title": "Longest Consecutive Sequence", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Find length of longest consecutive integer sequence in unsorted array.\n\nHashSet approach:\n• Add all elements to set\n• For each element, if (element-1) NOT in set → sequence start\n• Count consecutive elements from there\n\nTime: O(n) | Space: O(n)", "examples": [{"input": "arr=[100,4,200,1,3,2]", "output": "4 (sequence: 1,2,3,4)"}], "key_concepts": ["HashSet", "sequence start detection", "O(n)"]},
    {"title": "Set Matrix Zeroes", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "If element is 0, set its entire row and column to 0 in-place.\n\nOptimal:\n• Use first row and first column as flags\n• Track separately if first row/col themselves have zero\n• Fill zeros based on flags\n\nTime: O(m*n) | Space: O(1)", "key_concepts": ["first row/col as flags", "in-place", "O(1) space"]},
    {"title": "Rotate Matrix by 90 degrees", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Rotate n×n matrix 90 degrees clockwise in-place.\n\nAlgorithm:\n1. Transpose (swap matrix[i][j] with matrix[j][i])\n2. Reverse each row\n\nTime: O(n²) | Space: O(1)", "examples": [{"input": "[[1,2,3],[4,5,6],[7,8,9]]", "output": "[[7,4,1],[8,5,2],[9,6,3]]"}], "key_concepts": ["transpose", "row reversal", "in-place rotation"]},
    {"title": "Pascal's Triangle", "difficulty": "Medium", "step": "Step 3: Solve Problems on Arrays", "description": "Generate first numRows of Pascal's Triangle.\n\nEach number = sum of two above.\n\nApproach:\n• Row 0 = [1]\n• Each row starts/ends with 1; middle = prev[j-1] + prev[j]\n\nTime: O(n²) | Space: O(n²)", "examples": [{"input": "numRows=5", "output": "[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]"}], "key_concepts": ["2D array", "row building", "combinatorics"]},
    {"title": "Majority Element (n/3 times)", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Find all elements appearing more than n/3 times. At most 2 such elements exist.\n\nExtended Boyer-Moore:\n• Maintain two candidates and counts\n• Eliminate pairs of different candidates\n• Verify both in second pass\n\nTime: O(n) | Space: O(1)", "key_concepts": ["extended Boyer-Moore", "two candidates", "n/3 threshold"]},
    {"title": "3 Sum", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Find all unique triplets summing to 0.\n\nApproach:\n• Sort array\n• For each i, use two-pointer on remainder\n• Skip duplicates for i, left, right\n\nTime: O(n²) | Space: O(1) extra", "key_concepts": ["sort + two pointers", "deduplication", "triplets"]},
    {"title": "4 Sum", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Find all unique quadruplets summing to target.\n\nApproach:\n• Sort array\n• Two nested loops + two-pointer technique\n• Skip duplicates at each level\n\nTime: O(n³) | Space: O(1) extra", "key_concepts": ["nested loops", "two pointers", "quadruplets", "deduplication"]},
    {"title": "Largest subarray with 0 sum", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Find length of longest subarray with sum = 0.\n\nPrefix Sum + HashMap:\n• Track running prefix sum\n• If prefixSum==0: maxLen = i+1\n• If prefixSum seen before: length = i - map[prefixSum]\n\nTime: O(n) | Space: O(n)", "key_concepts": ["prefix sum", "hashmap", "zero-sum subarray"]},
    {"title": "Count number of subarrays with given XOR k", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Count subarrays whose XOR equals k.\n\nPrefix XOR + HashMap:\n• Compute prefix XOR; if XOR==k: count++\n• If (XOR^k) in map: add map[XOR^k] to count\n• Store prefix XOR in map\n\nTime: O(n) | Space: O(n)", "key_concepts": ["XOR properties", "prefix XOR", "hashmap"]},
    {"title": "Merge Overlapping Subintervals", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Merge all overlapping intervals.\n\nApproach:\n• Sort by start time\n• If current overlaps with last merged, extend it\n• Else add as new interval\n\nTime: O(n log n) | Space: O(n)", "key_concepts": ["sorting", "overlap detection", "interval merging"]},
    {"title": "Merge two sorted arrays without extra space", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Merge two sorted arrays without extra space.\n\nGap Method:\n• gap = ceil((m+n)/2)\n• Compare and swap elements at distance gap\n• Halve gap each iteration\n\nTime: O((m+n) log(m+n)) | Space: O(1)", "key_concepts": ["gap method", "O(1) space", "in-place merge"]},
    {"title": "Find the repeating and missing number", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Array of size n has one number repeated and one missing (range 1..n). Find both.\n\nMath approach:\n• S = sum of array, S2 = sum of squares\n• Use expected sum and expected sum² formulas\n• Solve for (repeating - missing) and (repeating + missing)\n\nTime: O(n) | Space: O(1)", "key_concepts": ["sum formula", "sum of squares", "equation solving"]},
    {"title": "Count Inversions", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Count pairs (i,j) where i<j but arr[i]>arr[j].\n\nMerge Sort approach:\n• During merge, when right element placed before left elements, all remaining left elements are inversions\n\nTime: O(n log n) | Space: O(n)", "key_concepts": ["merge sort", "inversion count", "divide and conquer"]},
    {"title": "Reverse Pairs", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Count pairs where i<j and arr[i] > 2*arr[j].\n\nModified Merge Sort:\n• For each left element, count valid right elements using two pointers\n• Then do actual merge\n\nTime: O(n log n) | Space: O(n)", "key_concepts": ["modified merge sort", "two pointers", "condition counting"]},
    {"title": "Maximum Product Subarray", "difficulty": "Hard", "step": "Step 3: Solve Problems on Arrays", "description": "Find contiguous subarray with maximum product.\n\nApproach:\n• Track both max and min products (min matters: negative × negative = positive)\n• maxProd = max(arr[i], maxProd*arr[i], minProd*arr[i])\n• Similarly update minProd\n\nTime: O(n) | Space: O(1)", "key_concepts": ["max and min tracking", "negative numbers", "product subarray"]},

    # Step 4
    {"title": "Binary Search to find X in sorted array", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Classic binary search on a sorted array.\n\nAlgorithm:\n• low=0, high=n-1\n• mid=(low+high)/2\n• arr[mid]==target → return mid\n• arr[mid]<target → low=mid+1\n• else → high=mid-1\n• Return -1 if not found\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[1,3,5,7,9], target=5", "output": "2"}, {"input": "arr=[1,2,3], target=4", "output": "-1"}], "key_concepts": ["binary search", "low/high/mid", "O(log n)"]},
    {"title": "Implement Lower Bound", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Find first index where arr[i] >= target.\n\nApproach:\n• If arr[mid] >= target: ans=mid, high=mid-1\n• Else: low=mid+1\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[1,2,2,3], target=2", "output": "1"}], "key_concepts": ["lower bound", "binary search variant"]},
    {"title": "Implement Upper Bound", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Find first index where arr[i] > target.\n\nApproach:\n• If arr[mid] > target: ans=mid, high=mid-1\n• Else: low=mid+1\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[1,2,2,3], target=2", "output": "3"}], "key_concepts": ["upper bound", "binary search variant"]},
    {"title": "Search Insert Position", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Return index of target if found; else return insertion position. Equivalent to lower bound.\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[1,3,5,6], target=5", "output": "2"}, {"input": "arr=[1,3,5,6], target=2", "output": "1"}], "key_concepts": ["lower bound", "insertion position"]},
    {"title": "Floor and Ceil in Sorted Array", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Floor: largest element <= target. Ceil: smallest element >= target.\n\n• Floor = largest arr[mid] <= target (binary search)\n• Ceil = lower bound\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[1,2,8,10,11], target=5", "output": "Floor=2, Ceil=8"}], "key_concepts": ["floor", "ceil", "binary search variants"]},
    {"title": "Find first and last occurrence of a given number", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Find first and last index of target in sorted array.\n\nApproach:\n• Binary search twice: once biasing left (first), once biasing right (last)\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[5,7,7,8,8,10], target=8", "output": "[3,4]"}], "key_concepts": ["first/last occurrence", "two binary searches"]},
    {"title": "Count occurrences of a number in a sorted array", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Count how many times target appears.\n\nApproach:\n• Find first and last occurrence\n• Count = lastIndex - firstIndex + 1\n\nTime: O(log n) | Space: O(1)", "key_concepts": ["first/last occurrence", "count formula"]},
    {"title": "Search in Rotated Sorted Array I", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Search target in sorted+rotated array (all distinct).\n\nApproach:\n• Determine which half is sorted\n• If target in sorted half, search there; else search other half\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[4,5,6,7,0,1,2], target=0", "output": "4"}], "key_concepts": ["rotated array", "sorted half detection", "binary search"]},
    {"title": "Search in Rotated Sorted Array II", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Sorted+rotated array with duplicates.\n\nExtra: When arr[low]==arr[mid]==arr[high]: low++, high--\n\nTime: O(log n) avg, O(n) worst | Space: O(1)", "key_concepts": ["duplicates handling", "shrink both ends"]},
    {"title": "Find minimum in Rotated Sorted Array", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Find minimum element in sorted+rotated array.\n\nApproach:\n• If arr[mid] > arr[high]: min is in right half (low=mid+1)\n• Else: min is in left half including mid (high=mid)\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[3,4,5,1,2]", "output": "1"}], "key_concepts": ["rotation point", "minimum detection"]},
    {"title": "Find out how many times array has been rotated", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Sorted array rotated k times. k = index of minimum element.\n\nUse binary search to find minimum element's index.\n\nTime: O(log n) | Space: O(1)", "key_concepts": ["rotation count", "minimum index"]},
    {"title": "Single element in a Sorted Array", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Every element appears twice except one. Find it.\n\nApproach:\n• In untampered left half, pairs are at (even, odd) indices\n• Check mid parity to determine which half single is in\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[1,1,2,3,3,4,4,8,8]", "output": "2"}], "key_concepts": ["index parity", "pair detection", "binary search"]},
    {"title": "Find peak element", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Peak element is greater than its neighbors. Find any peak index.\n\nApproach:\n• If arr[mid] > arr[mid+1]: peak in left half (including mid)\n• Else: peak in right half\n\nTime: O(log n) | Space: O(1)", "key_concepts": ["peak detection", "mountain property"]},
    {"title": "Find square root of a number in O(log n)", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Find integer square root (floor) of n.\n\nApproach:\n• Binary search on [0, n]\n• If mid*mid <= n: ans=mid, low=mid+1\n• Else: high=mid-1\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "n=16", "output": "4"}, {"input": "n=8", "output": "2"}], "key_concepts": ["binary search on answer", "integer sqrt"]},
    {"title": "Find the Nth root of a number", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Find Nth root of M. Return -1 if not perfect root.\n\nApproach:\n• Binary search on [1, M]\n• mid^n == M → return mid\n• mid^n < M → low=mid+1\n• else → high=mid-1\n\nTime: O(n log M) | Space: O(1)", "key_concepts": ["binary search on answer", "Nth root", "power check"]},
    {"title": "Koko Eating Bananas", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Minimum speed k to eat all piles in h hours.\n\nBinary search on answer k in [1, max(piles)]:\n• hours = sum(ceil(pile/k))\n• If hours <= h: try smaller k; else try larger\n\nTime: O(n log(max)) | Space: O(1)", "examples": [{"input": "piles=[3,6,7,11], h=8", "output": "4"}], "key_concepts": ["binary search on answer", "ceil division", "feasibility check"]},
    {"title": "Minimum days to make M bouquets", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Minimum day to make M bouquets of K adjacent bloomed roses.\n\nBinary search on [min(days), max(days)]:\n• For day d, count bouquets possible\n• If bouquets >= M: try earlier; else try later\n\nTime: O(n log(max-min)) | Space: O(1)", "key_concepts": ["binary search on time", "adjacent counting", "greedy feasibility"]},
    {"title": "Find the smallest divisor given a threshold", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Smallest divisor such that sum(ceil(arr[i]/divisor)) <= threshold.\n\nBinary search in [1, max(arr)].\n\nTime: O(n log(max)) | Space: O(1)", "key_concepts": ["binary search on divisor", "ceil sum", "threshold"]},
    {"title": "Capacity to Ship Packages within D Days", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Minimum ship capacity to ship all packages in D days (in order).\n\nBinary search in [max(weights), sum(weights)]:\n• Simulate days needed for given capacity\n• If days <= D: try lower\n\nTime: O(n log(sum)) | Space: O(1)", "examples": [{"input": "weights=[1,2,3,4,5,6,7,8,9,10], days=5", "output": "15"}], "key_concepts": ["binary search on capacity", "greedy simulation", "feasibility"]},
    {"title": "Kth Missing Positive Number", "difficulty": "Easy", "step": "Step 4: Binary Search", "description": "Kth missing positive number in sorted array.\n\nBinary Search:\n• At index i: missing count = arr[i] - (i+1)\n• Find first index where missing >= k\n• Answer = arr[low-1] + (k - missing_before_low)\n\nTime: O(log n) | Space: O(1)", "examples": [{"input": "arr=[2,3,4,7,11], k=5", "output": "9"}], "key_concepts": ["missing count formula", "binary search on count"]},
    {"title": "Aggressive Cows", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Place C cows in N stalls to maximise minimum distance between any two cows.\n\nApproach:\n• Sort stalls\n• Binary search on minimum distance\n• Greedy check: can C cows fit with at least this distance?\n\nTime: O(n log n) | Space: O(1)", "examples": [{"input": "stalls=[1,2,4,8,9], cows=3", "output": "3"}], "key_concepts": ["binary search on answer", "greedy placement", "maximum of minimum"]},
    {"title": "Allocate Books", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Allocate contiguous books to M students minimising maximum pages any student gets.\n\nBinary search on max pages in [max(arr), sum(arr)]:\n• Check if allocation possible for M students\n\nTime: O(n log(sum)) | Space: O(1)", "examples": [{"input": "books=[12,34,67,90], students=2", "output": "113"}], "key_concepts": ["binary search on answer", "contiguous allocation", "feasibility check"]},
    {"title": "Split array - Largest Sum", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Split array into m subarrays to minimize largest subarray sum. Same logic as Allocate Books.\n\nTime: O(n log(sum)) | Space: O(1)", "examples": [{"input": "arr=[7,2,5,10,8], m=2", "output": "18"}], "key_concepts": ["binary search on answer", "minimize maximum", "partition"]},
    {"title": "Minimize Max Distance to Gas Station", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Add K stations to minimise maximum distance between adjacent stations.\n\nBinary search on distance (floating point):\n• Count stations needed = sum(floor(gap/d))\n• Adjust until sufficient precision\n\nTime: O(n log(max/eps)) | Space: O(1)", "key_concepts": ["floating point binary search", "greedy insertion", "station counting"]},
    {"title": "Median of 2 sorted arrays", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Find median of two sorted arrays in O(log(min(m,n))).\n\nApproach:\n• Binary search on smaller array\n• Partition both so left half has (m+n)/2 elements\n• Check validity: max(left) <= min(right)\n\nTime: O(log(min(m,n))) | Space: O(1)", "examples": [{"input": "arr1=[1,3], arr2=[2]", "output": "2.0"}], "key_concepts": ["partition", "binary search", "median condition"]},
    {"title": "K-th Element of two sorted arrays", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Kth smallest in union of two sorted arrays.\n\nExtend median-of-two-arrays technique with binary search.\n\nTime: O(log(min(m,n))) | Space: O(1)", "key_concepts": ["binary search", "kth element", "partition"]},
    {"title": "Row with maximum 1s", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "In row-wise sorted binary matrix, find row with most 1s.\n\nApproach:\n• For each row, binary search for first 1\n• Count 1s = cols - firstOneIndex\n• Track maximum\n\nTime: O(n log m) | Space: O(1)", "key_concepts": ["binary search per row", "first 1 index", "count optimization"]},
    {"title": "Search in a 2D Matrix", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Matrix sorted row-wise and first element of each row > last element of previous. Search target.\n\nTreat as 1D sorted array:\n• mid → row=mid/cols, col=mid%cols\n\nTime: O(log(m*n)) | Space: O(1)", "examples": [{"input": "matrix=[[1,3,5,7],[10,11,16,20],[23,30,34,60]], target=3", "output": "true"}], "key_concepts": ["1D mapping", "virtual index", "binary search"]},
    {"title": "Search in a 2D Matrix II", "difficulty": "Medium", "step": "Step 4: Binary Search", "description": "Matrix sorted in rows and columns individually. Search target.\n\nStaircase Search from top-right:\n• If arr[r][c]==target → found\n• If arr[r][c]>target → c--\n• If arr[r][c]<target → r++\n\nTime: O(m+n) | Space: O(1)", "key_concepts": ["staircase search", "top-right corner", "O(m+n)"]},
    {"title": "Find a Peak Element II", "difficulty": "Hard", "step": "Step 4: Binary Search", "description": "Find any peak in 2D matrix (greater than all neighbors).\n\nBinary search on columns:\n• In mid column find row with max element\n• If local peak, return; else move toward larger neighbor\n\nTime: O(m log n) | Space: O(1)", "key_concepts": ["2D binary search", "column binary search", "local peak"]},
]


def upload_lessons():
    db = boto3.resource(
        "dynamodb",
        region_name=os.environ.get("DYNAMODB_REGION", os.environ.get("AWS_REGION", "ap-south-1")),
        aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.environ.get("AWS_SECRET_ACCESS_KEY"),
    )
    table = db.Table("aquire-lessons")

    success = 0
    failed = 0

    for lesson in LESSONS:
        item = {
            "course_id": "dsa",
            "lesson_id": lesson["title"],
            "title": lesson["title"],
            "difficulty": lesson.get("difficulty", ""),
            "step": lesson.get("step", ""),
            "description": lesson.get("description", ""),
            "key_concepts": lesson.get("key_concepts", []),
            "examples": lesson.get("examples", []),
            "transcript_summary": lesson.get("description", ""),
        }
        try:
            table.put_item(Item=item)
            print(f"✅ {lesson['title']}")
            success += 1
        except Exception as e:
            print(f"❌ {lesson['title']}: {e}")
            failed += 1

    print(f"\nDone: {success} uploaded, {failed} failed.")


if __name__ == "__main__":
    upload_lessons()
